import Head from 'next/head'
import React from 'react'

function Workkflow() {
  return (
    <div>
    <Head>
  {/* <title>Expert || Any Service | Any Time | Any Where</title>
  <meta name="description" content="Generated by create next app" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="icon" href="/favicon.ico" /> */}
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous"
   />
</Head>
<div className='col-md-12 '>
  <div className='row'>
      <div className='col-md-6 col-6 px-0'>
          <div className='col-md-12  text-right'>
              <p className='color_red_workflow'><b>WORKFLOW</b></p>
              <div className='col-md-12 px-0 text-right'>
              <p className='font_weight_stream'>A Streamlined<br/> Approach to Project<br/> Management</p>
              </div>
          </div>
          <div className='col-md-12 px-0'>
          <img className='img-fluid img_bulb_top' src='https://1864597015.rsc.cdn77.org/selteqreact/images/bulb.png' />
          </div>
      </div>
      <div className='col-md-6 col-6 px-0 '>
          <img className='img-fluid width_img_land' src='https://1864597015.rsc.cdn77.org/selteqreact/images/moblady.png' />
      </div>
  </div>
  <div className='col-md-12 pl-1'>
      <h5 className='text_align_work'><b>Idea</b></h5>
  </div>
  <div className='col-md-12 px-1'>
      <h6 className='sub_para_text'>We nurture a long-term partnership to get started on identifying the overall requirement of your product & detailed feasibility analysis.</h6>
  </div>
  <div className='col-md-12 px-2'>
  <img className='img-fluid width_img_land' src='https://1864597015.rsc.cdn77.org/selteqreact/images/box.png' />
  </div>
  <div className='col-md-12 px-2 pt-2 text-right'>
      <h5 className='text_align_work'><b>Prototype</b></h5>
  </div>
  <div className='col-md-12 px-2 text-right'>
      <h6 className='sub_para_text'>A prototype with a project structure and mock-ups in a clickable form. Modelling everything from functionality to objectives of the product.</h6>
  </div>
  <div className='col-md-12 px-2'>
  <img className='img-fluid width_img_land' src='https://1864597015.rsc.cdn77.org/selteqreact/images/code.png' />
  </div>
  <div className='col-md-12 px-2 pt-2 text-left'>
      <h5 className='text_align_work'><b>Development</b></h5>
  </div>
  <div className='col-md-12 px-2 text-left'>
      <h6 className='sub_para_text'>Keeping SDLC in view, our development release cycle proceeds from alpha, beta to the actual production build.</h6>
  </div>
  <div className='col-md-12 px-2'>
  <img className='img-fluid width_img_land' src='https://1864597015.rsc.cdn77.org/selteqreact/images/lighthouse.png' />
  </div>
  <div className='col-md-12 px-2 pt-2 text-right'>
      <h5 className='text_align_work'><b>Deployment</b></h5>
  </div>
  <div className='col-md-12 px-2 text-right'>
      <h6 className='sub_para_text'>We work in small teams using iterative approaches. The final deployment takes place with full functionality & user feedback.</h6>
  </div>
  <div className='col-md-12 px-2'>
  <img className='img-fluid width_img_land' src='https://1864597015.rsc.cdn77.org/selteqreact/images/stock.png' />
  </div>
  <div className='col-md-12 px-2 pt-2 text-left'>
      <h5 className='text_align_work'><b>Scaling</b></h5>
  </div>
  <div className='col-md-12 px-2 text-left'>
      <h6 className='sub_para_text'>Product has flown off the shelves and has been launched in the market. So, you’ll be seeking dedicated maintenance services & scaling.</h6>
  </div>
  
</div>
</div>
  )
}

export default Workkflow